alpha: 10.0
alpha_final: null
alpha_init: null
base_path: /home/hawk/Documents/school/dataset/project/cleaned
beta: 0.01
categorical_columns:
- Src Port
- Dst Port
- Protocol
categorical_weight: 2.0
constraint_method: hard
convert_labels: false
dataset: CICDDoS2019
exclude_labels: []
kernel_method: exponential
kernel_sigma: 0.01
known_labels:
- WebDDoS
- DrDoS_NetBIOS
- DrDoS_SNMP
labeled_rate: 0.2
learning_rate: 1.0e-05
max_iter: 100
n_samples_per_label: 1000
normalize_numerical: none
numerical_weight: 1.0
random_state: 42
tags:
- labels
tol: 1e-6
use_known_no_labeled: false
use_labels: []
