alpha: 0.5
alpha_final: null
alpha_init: null
base_path: /home/hawk/Documents/school/dataset/project/sampled/n_100000_s_42
beta: 0.01
categorical_columns:
- Src Port
- Dst Port
- Protocol
categorical_weight: 2.0
constraint_method: hard
dataset: CICDDoS2019
exclude_labels:
- WebDDoS
- DrDoS_NetBIOS
- DrDoS_SNMP
kernel_method: exponential
kernel_sigma: 0.15
known_labels: []
labeled_rate: 0.2
learning_rate: 0.001
max_iter: 100
n_samples_per_label: 100
normalize_numerical: none
numerical_weight: 1.0
random_state: 42
relabel: false
tags:
- labels
tol: 1e-6
use_known_no_labeled: false
use_labels: []
