dvc exp run -S known_labels='[]' --queue
dvc exp run -S known_labels='["Heartbleed"]' --queue
dvc exp run -S known_labels='["Infiltration"]' --queue
dvc exp run -S known_labels='["Bot"]' --queue
dvc exp run -S known_labels='["DoS"]' --queue
dvc exp run -S known_labels='["DDoS"]' --queue
dvc exp run -S known_labels='["SSH-Patator"]' --queue
dvc exp run -S known_labels='["PortScan"]' --queue
dvc exp run -S known_labels='["FTP-Patator"]' --queue
dvc exp run -S known_labels='["Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS", "DDoS"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "Bot", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Infiltration", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "Bot", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "DDoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Heartbleed", "SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "DDoS", "SSH-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "DDoS", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "DDoS", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "DDoS", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "Bot", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "DDoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Infiltration", "SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "SSH-Patator", "PortScan"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "SSH-Patator", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "SSH-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "DDoS", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "DDoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["Bot", "SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "PortScan", "FTP-Patator"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "PortScan", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "SSH-Patator", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "DDoS", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DoS", "SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
dvc exp run -S known_labels='["DDoS", "SSH-Patator", "PortScan", "FTP-Patator", "Web Attack"]' --queue
